import React from "react";

export default function PrivacyPolicy() {
    return (
        <main style={{padding: "1rem 0"}}>

            <div className={"pb-5"}>
                <div className="pm-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    <h1 className="display-3">Privacy Policy</h1>
                </div>

                <div className={"container g-4"}>

                    <div>
                        <p>
                            Roman Makarskiy (Romancha) built the Work & Rest app as a Freemium app. This SERVICE is
                            provided by Romancha at no cost and is intended for use as is.
                        </p>
                        <p>
                            This page is used to inform visitors regarding my policies with the collection, use, and
                            disclosure of Personal Information if anyone decided to use my Service.
                        </p>
                        <p>
                            If you choose to use my Service, then you agree to the collection and use of information in
                            relation to this policy. The Personal Information that I collect is used for providing and
                            improving the Service. I will not use or share your information with anyone except as
                            described in this Privacy Policy.
                        </p>
                        <p>
                            The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions,
                            which is accessible at Work&Rest unless otherwise defined in this Privacy Policy.
                        </p>
                    </div>

                    <div>
                        <h3>Information Collection and Use</h3>
                        <p>
                            For a better experience, statistics and ability to cloud sync, while using our Service, I
                            may require you to provide us with certain personally identifiable information, including
                            but not limited to google account email, unique id, name, profile photo and any content
                            generated by user.
                        </p>
                        <p>
                            Unless specified otherwise, all data requested by Work&Rest is mandatory and failure to
                            provide this data may make it impossible for Work&Rest to provide its services. In cases
                            where Service specifically states that some data is not mandatory, Users are free not to
                            communicate this data without consequences to the availability or the functioning of the
                            Service.
                        </p>
                        <p>
                            Users are responsible for any third-party Personal Data obtained, published or shared
                            through Service and confirm that they have the third party’s consent to provide the Data to
                            the Owner.
                        </p>
                        <p>
                            The app does use third party services that may collect information used to identify you.
                        </p>
                        <p>
                            Link to privacy policy of third party service providers used by the app
                        </p>
                        <ul>
                            <li><a href="https://www.google.com/policies/privacy/" target="_blank"
                                   rel="noopener noreferrer">Google Play Services</a></li>
                            <li><a href="https://support.google.com/admob/answer/6128543?hl=en" target="_blank"
                                   rel="noopener noreferrer">AdMob</a></li>
                            <li><a href="https://firebase.google.com/policies/analytics" target="_blank"
                                   rel="noopener noreferrer">Google Analytics for Firebase</a></li>
                            <li><a href="https://firebase.google.com/support/privacy/" target="_blank"
                                   rel="noopener noreferrer">Firebase Crashlytics</a></li>
                            <li><a href="https://www.facebook.com/about/privacy/update/printable" target="_blank"
                                   rel="noopener noreferrer">Facebook</a></li>
                        </ul>
                    </div>

                    <div>
                        <h3>Legal basis of processing</h3>
                        <p>
                            The Owner may process Personal Data relating to Users if one of the following applies:
                        </p>
                        <ul>
                            <li>Users have given their consent for one or more specific purposes. Note: Under some
                                legislations the Owner may be allowed to process Personal Data until the User objects to
                                such processing (“opt-out”), without having to rely on consent or any other of the
                                following legal bases. This, however, does not apply, whenever the processing of
                                Personal Data is subject to European data protection law;
                            </li>
                            <li>provision of Data is necessary for the performance of an agreement with the User and/or
                                for any pre-contractual obligations thereof;
                            </li>
                            <li>processing is necessary for compliance with a legal obligation to which the Owner is
                                subject;
                            </li>
                            <li>processing is related to a task that is carried out in the public interest or in the
                                exercise of official authority vested in the Owner;
                            </li>
                            <li>processing is necessary for the purposes of the legitimate interests pursued by the
                                Owner or by a third party.
                            </li>
                        </ul>
                        <p>
                            In any case, the Owner will gladly help to clarify the specific legal basis that applies to
                            the processing, and in particular whether the provision of Personal Data is a statutory or
                            contractual requirement, or a requirement necessary to enter into a contract.
                        </p>
                    </div>

                    <div>
                        <h3>Place</h3>
                        <p>The Data is processed at the Owner’s operating offices and in any other places where the
                            parties involved in the processing are located.</p>
                        <p>
                            Depending on the User’s location, data transfers may involve transferring the User’s Data to
                            a country other than their own. To find out more about the place of processing of such
                            transferred Data, Users can check the section containing details about the processing of
                            Personal Data.
                        </p>
                        <p>
                            Users are also entitled to learn about the legal basis of Data transfers to a country
                            outside the European Union or to any international organization governed by public
                            international law or set up by two or more countries, such as the UN, and about the security
                            measures taken by the Owner to safeguard their Data.
                        </p>
                        <p>
                            If any such transfer takes place, Users can find out more by checking the relevant sections
                            of this document or inquire with the Owner using the information provided in the contact
                            section.
                        </p>
                    </div>

                    <div>
                        <h3>Retention time</h3>
                        <p>
                            Personal Data shall be processed and stored for as long as required by the purpose they have
                            been collected for.
                        </p>
                        <p>
                            Therefore:
                        </p>
                        <ul>
                            <li>Personal Data collected for purposes related to the performance of a contract between
                                the Owner and the User shall be retained until such contract has been fully performed.
                            </li>
                            <li>Personal Data collected for the purposes of the Owner’s legitimate interests shall be
                                retained as long as needed to fulfill such purposes. Users may find specific information
                                regarding the legitimate interests pursued by the Owner within the relevant sections of
                                this document or by contacting the Owner.
                            </li>
                        </ul>
                        <p>
                            The Owner may be allowed to retain Personal Data for a longer period whenever the User has
                            given consent to such processing, as long as such consent is not withdrawn. Furthermore, the
                            Owner may be obliged to retain Personal Data for a longer period whenever required to do so
                            for the performance of a legal obligation or upon order of an authority.
                        </p>
                        <p>
                            Once the retention period expires, Personal Data shall be deleted. Therefore, the right to
                            access, the right to erasure, the right to rectification and the right to data portability
                            cannot be enforced after expiration of the retention period.
                        </p>
                    </div>

                    <div>
                        <h3>Service Providers</h3>
                        <p>
                            I may employ third-party companies and individuals due to the following reasons:
                        </p>
                        <ul>
                            <li>To facilitate our Service;</li>
                            <li>To provide the Service on our behalf;</li>
                            <li>To perform Service-related services; or</li>
                            <li>To assist us in analyzing how our Service is used.</li>
                        </ul>
                        <p>
                            I want to inform users of this Service that these third parties have access to your Personal
                            Information. The reason is to perform the tasks assigned to them on our behalf. However,
                            they are obligated not to disclose or use the information for any other purpose.
                        </p>
                    </div>

                    <div>
                        <h3>Security</h3>
                        <p>
                            I takes appropriate security measures to prevent unauthorized access, disclosure,
                            modification, or unauthorized destruction of the Data. I value your trust in providing us
                            your Personal Information, thus we are striving to use commercially acceptable means of
                            protecting it. But remember that no method of transmission over the internet, or method of
                            electronic storage is 100% secure and reliable, and I cannot guarantee its absolute
                            security.
                        </p>
                    </div>

                    <div>
                        <h3>Log Data</h3>
                        <p>
                            I want to inform you that whenever you use my Service, in a case of an error in the app I
                            collect data and information (through third party products) on your phone called Log Data.
                            This Log Data may include information such as your device Internet Protocol (“IP”) address,
                            device name, operating system version, the configuration of the app when utilizing my
                            Service, the time and date of your use of the Service, and other statistics.
                        </p>
                    </div>

                    <div>
                        <h3>Cookies</h3>
                        <p>
                            Cookies are files with a small amount of data that are commonly used as anonymous unique
                            identifiers. These are sent to your browser from the websites that you visit and are stored
                            on your device’s internal memory.
                        </p>
                        <p>
                            This Service does not use these “cookies” explicitly. However, the app may use third party
                            code and libraries that use “cookies” to collect information and improve their services. You
                            have the option to either accept or refuse these cookies and know when a cookie is being
                            sent to your device. If you choose to refuse our cookies, you may not be able to use some
                            portions of this Service.
                        </p>
                    </div>

                    <div>
                        <h3>Links to Other Sites</h3>
                        <p>
                            This Service may contain links to other sites. If you click on a third-party link, you will
                            be directed to that site. Note that these external sites are not operated by me. Therefore,
                            I strongly advise you to review the Privacy Policy of these websites. I have no control over
                            and assume no responsibility for the content, privacy policies, or practices of any
                            third-party sites or services.
                        </p>
                    </div>

                    <div>
                        <h3>Children’s Privacy</h3>
                        <p>
                            These Services do not address anyone under the age of 13. I do not knowingly collect
                            personally identifiable information from children under 13. In the case I discover that a
                            child under 13 has provided me with personal information, I immediately delete this from our
                            servers. If you are a parent or guardian and you are aware that your child has provided us
                            with personal information, please contact me so that I will be able to do necessary actions.
                        </p>
                    </div>

                    <div>
                        <h3>The rights of Users</h3>
                        <p>
                            Users may exercise certain rights regarding their Data processed by the Owner.
                        </p>
                        <p>
                            In particular, Users have the right to do the following:
                        </p>
                        <ul>
                            <li><b>Withdraw their consent at any time.</b> Users have the right to withdraw consent
                                where they have previously given their consent to the processing of their Personal Data.
                            </li>
                            <li><b>Object to processing of their Data.</b> Users have the right to object to the
                                processing of their Data if the processing is carried out on a legal basis other than
                                consent. Further details are provided in the dedicated section below.
                            </li>
                            <li><b>Access their Data.</b> Users have the right to learn if Data is being processed by
                                the Owner, obtain disclosure regarding certain aspects of the processing and obtain a
                                copy of the Data undergoing processing.
                            </li>
                            <li><b>Verify and seek rectification.</b> Users have the right to verify the accuracy of
                                their Data and ask for it to be updated or corrected.
                            </li>
                            <li><b>Restrict the processing of their Data.</b> Users have the right, under certain
                                circumstances, to restrict the processing of their Data. In this case, the Owner will
                                not process their Data for any purpose other than storing it.
                            </li>
                            <li><b>Have their Personal Data deleted or otherwise removed.</b> Users have the right,
                                under certain circumstances, to obtain the erasure of their Data from the Owner.
                            </li>
                            <li><b>Receive their Data and have it transferred to another controller.</b> Users have the
                                right to receive their Data in a structured, commonly used and machine readable format
                                and, if technically feasible, to have it transmitted to another controller without any
                                hindrance. This provision is applicable provided that the Data is processed by automated
                                means and that the processing is based on the User’s consent, on a contract which the
                                User is part of or on pre-contractual obligations thereof.
                            </li>
                            <li><b>Lodge a complaint.</b> Users have the right to bring a claim before their competent
                                data protection authority.
                            </li>
                        </ul>

                        <h5>Details about the right to object to processing</h5>
                        <p>
                            Where Personal Data is processed for a public interest, in the exercise of an official
                            authority vested in the Owner or for the purposes of the legitimate interests pursued by the
                            Owner, Users may object to such processing by providing a ground related to their particular
                            situation to justify the objection.
                        </p>

                        <h5>How to exercise these rights</h5>
                        <p>
                            Any requests to exercise User rights can be directed to the Owner through the contact
                            details provided in this document. These requests can be exercised free of charge and will
                            be addressed by the Owner as early as possible and always within one month.
                        </p>
                    </div>

                    <div>
                        <h3>Changes to This Privacy Policy</h3>
                        <p>I may update our Privacy Policy from time to time. Thus, you are advised to review this page
                            periodically for any changes. I will notify you of any changes by posting the new Privacy
                            Policy on this page.
                        </p>
                        <p>
                            This policy is effective as of 2020-10-25
                        </p>
                    </div>

                    <div>
                        <h3>Contact Us</h3>
                        <p>
                            If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact
                            me at wr@romancha.org.
                        </p>
                        <p>This privacy policy page was created at&nbsp;
                            <a href="https://privacypolicytemplate.net/"
                               target="_blank"
                               rel="noopener noreferrer">privacypolicytemplate.net</a>&nbsp;and
                            modified/generated by&nbsp;<a href="https://app-privacy-policy-generator.firebaseapp.com/"
                                                          target="_blank" rel="noopener noreferrer">App Privacy Policy
                                Generator</a>
                        </p>
                    </div>
                </div>
            </div>

        </main>
    );
}