version: '2'
services:
  wrpomodoro:
    image: trueromancha/wr-pomodoro-site:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d